import type { Metadata, Viewport } from 'next';
import { Inter } from 'next/font/google';
import '@/scss/global.scss';

import { Header, Footer } from '@/components/shared';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1.0,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={inter.className}>
        <div className="wrapper">
          <Header />
          <main className="main"> {children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
